# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: pretty
#permalink: /:categories/:year/:month/:day/:title 

exclude: ['public', 'test_metric', 'siteSpec', 'bin', 'vendor', 'lessons', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru', 'README.md', '.rvmrc', '.rbenv-version', 'newrelic.yml']
#auto: true
pygments: true
#markdown: maruku
relative_permalinks: true
#baseurl:     /
markdown: kramdown
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

prose:
   metadata:
      "_posts": |
         layout: post
         title: ""
         description:
         category:
         tags: []
         source:
            url:
            title:
         llist:
         image:
            url:
            caption:

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : "stderr | log"
tagline: "an io scratch pad"
description: "guesstimating abnormality"
author :
  name : Jason Mitchell
  email : jason.j.mitchell+myspambin@gmail.com
  gravatar: 239eab777855b23b5f4a0a8c37c8592c
  github : mitchejj
  twitter : mitchejj
timezone: America/New_York
asset:
   #css: //netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css
   css: //netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.no-icons.min.css
   tweaks: /../assets/nuts_n_bolts.css
   js: //netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js
   icons: //netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css
   #jquery: //code.jquery.com/jquery-1.10.2.min.js
   jquery: //ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js
icon:
   visited: icon-bookmark
   unvisited: icon-bookmark-empty
   widget: icon-ellipsis-vertical
   list: icon-caret-right
paginate: 5
destination: public

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://stderr.me

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.2.13

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.com/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.com/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  BASE_PATH : false
  
  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex: 
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false
  
  
  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change theme here if needed.
  #
  about_path: /about/
  archive_path: /archive/
  categories_path : /categories/
  tags_path : /tags/

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments :
    provider : false
    disqus :
      short_name : 
    livefyre :
      site_id : 
    intensedebate :
      account : 
    facebook :
      appid : 
      num_posts: 
      width: 
      colorscheme:
      
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
    provider : false 
    google : 
        tracking_id :
    getclicky :
      site_id : 
    mixpanel :
        token :

  # Settings for sharing helper. 
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false
    
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
